#!/bin/bash
#
# Copyright (c) Authors: https://github.com/Gronis/overlayroot/graphs/contributors
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

# Add this file to /etc/default/armbian-motd to prompt the
# user at login that overlayroot is used on this system, and
# if it is currently protected/enabled or not.

THIS_SCRIPT="overlayroot"
MOTD_DISABLE=""

[[ -f /etc/default/armbian-motd ]] && . /etc/default/armbian-motd

for f in $MOTD_DISABLE; do
	[[ $f == $THIS_SCRIPT ]] && exit 0
done

HAS_OVERLAY=$(df / | grep overlay)
if [ ! "$HAS_OVERLAY" ]; then
        echo -e "\e[31mWARNING:\e[0m This system's sd card is not protected. Run \e[31menableoverlayroot\e[0m"
        echo -e            "         to enable protection after next reboot."
        echo

else
	echo -e "\e[31mNOTE:\e[0m This system is running overlayroot to protect the sd card."
	echo -e            "      All changes to / are stored in ram and reset after boot."
	echo -e            "      use \e[31mrootwork\e[0m script to disable until reboot."
	echo
	echo -e            "      Use \e[31mdisableoverlayroot\e[0m to completly disable even after"
	echo -e            "      reboot. Remember to enable again with \e[31menableoverlayroot\e[0m."
	echo
fi
