#!/bin/bash

# Restart script with sudo
if [ `id -u` -gt 0 ]; then
    exec sudo "$0" "$@"
fi


# Needs to start from root, and no slash on end
SRC_PATH=/var/lib/glusterd
TMP_PATH=/tmp/glusterd
SERVICE=glusterd

# glusterd.service was called glusterfs-server on older debian releases
if ! systemctl list-units --full -all | grep -Fq "$SERVICE"; then
	SERVICE=glusterfs-server
fi

set -e

echo "Stopping gluster..."
systemctl stop $SERVICE

echo "Storing gluster config..."

rm -rf "${TMP_PATH}"
cp -a "${SRC_PATH}" "${TMP_PATH}"
mount -o remount,rw "/overlay/lower"
rm -rf "/overlay/lower${SRC_PATH}.bak"
cp -a "/overlay/lower${SRC_PATH}" "/overlay/lower${SRC_PATH}.bak"
rm -rf "/overlay/lower${SRC_PATH}/"
cp -a "${TMP_PATH}/." "/overlay/lower/${SRC_PATH}/"
mount -o remount,ro "/overlay/lower" || {
    echo "Failed to remount $ROOT read-only, possibly because of an open file."
    echo "The best thing to do would be to reboot now"
}
rm -rf "${TMP_PATH}"

echo "Starting gluster..."
systemctl start $SERVICE

echo "Done"
exit 0
